// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: follow.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const listFollowers = `-- name: ListFollowers :many
SELECT
    u.id, u.username, u.avatar_url, u.bio
FROM follows f
JOIN users u ON f.follower_id = u.id
WHERE f.following_id = $1
ORDER BY f.created_at DESC
LIMIT $3 OFFSET $2
`

type ListFollowersParams struct {
	FollowingID uuid.UUID `json:"following_id"`
	OffsetCount int32     `json:"offset_count"`
	LimitCount  int32     `json:"limit_count"`
}

type ListFollowersRow struct {
	ID        uuid.UUID   `json:"id"`
	Username  string      `json:"username"`
	AvatarURL pgtype.Text `json:"avatar_url"`
	Bio       pgtype.Text `json:"bio"`
}

func (q *Queries) ListFollowers(ctx context.Context, arg ListFollowersParams) ([]ListFollowersRow, error) {
	rows, err := q.db.Query(ctx, listFollowers, arg.FollowingID, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFollowersRow{}
	for rows.Next() {
		var i ListFollowersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.AvatarURL,
			&i.Bio,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFollowing = `-- name: ListFollowing :many
SELECT
    u.id, u.username, u.avatar_url, u.bio
FROM follows f
JOIN users u ON f.following_id = u.id
WHERE f.follower_id = $1
ORDER BY f.created_at DESC
LIMIT $3 OFFSET $2
`

type ListFollowingParams struct {
	FollowerID  uuid.UUID `json:"follower_id"`
	OffsetCount int32     `json:"offset_count"`
	LimitCount  int32     `json:"limit_count"`
}

type ListFollowingRow struct {
	ID        uuid.UUID   `json:"id"`
	Username  string      `json:"username"`
	AvatarURL pgtype.Text `json:"avatar_url"`
	Bio       pgtype.Text `json:"bio"`
}

func (q *Queries) ListFollowing(ctx context.Context, arg ListFollowingParams) ([]ListFollowingRow, error) {
	rows, err := q.db.Query(ctx, listFollowing, arg.FollowerID, arg.OffsetCount, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFollowingRow{}
	for rows.Next() {
		var i ListFollowingRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.AvatarURL,
			&i.Bio,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const toggleFollow = `-- name: ToggleFollow :exec
INSERT INTO follows (
    follower_id, following_id
) VALUES (
    $1, $2
) ON CONFLICT (follower_id, following_id) DO NOTHING
`

type ToggleFollowParams struct {
	FollowerID  uuid.UUID `json:"follower_id"`
	FollowingID uuid.UUID `json:"following_id"`
}

func (q *Queries) ToggleFollow(ctx context.Context, arg ToggleFollowParams) error {
	_, err := q.db.Exec(ctx, toggleFollow, arg.FollowerID, arg.FollowingID)
	return err
}

const unfollow = `-- name: Unfollow :exec
DELETE FROM follows WHERE follower_id = $1 AND following_id = $2
`

type UnfollowParams struct {
	FollowerID  uuid.UUID `json:"follower_id"`
	FollowingID uuid.UUID `json:"following_id"`
}

func (q *Queries) Unfollow(ctx context.Context, arg UnfollowParams) error {
	_, err := q.db.Exec(ctx, unfollow, arg.FollowerID, arg.FollowingID)
	return err
}
