// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: like.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const toggleLike = `-- name: ToggleLike :exec
INSERT INTO likes (
    id, user_id, target_id, target_type
) VALUES (
    $1, $2, $3, $4
) ON CONFLICT (user_id, target_id, target_type) DO NOTHING
`

type ToggleLikeParams struct {
	ID         uuid.UUID `json:"id"`
	UserID     uuid.UUID `json:"user_id"`
	TargetID   uuid.UUID `json:"target_id"`
	TargetType int16     `json:"target_type"`
}

func (q *Queries) ToggleLike(ctx context.Context, arg ToggleLikeParams) error {
	_, err := q.db.Exec(ctx, toggleLike,
		arg.ID,
		arg.UserID,
		arg.TargetID,
		arg.TargetType,
	)
	return err
}
